import { DOCUMENT_INFO_ETICA_DEONTOLOGIA_TEXT } from './infoEticaDeontologia';
import { CODIGO_DEONTOLOGICO_TEXT } from './codigoDeontologico';

export { DOCUMENT_INFO_ETICA_DEONTOLOGIA_TEXT, CODIGO_DEONTOLOGICO_TEXT };

export const KNOWLEDGE_BASE = `
${DOCUMENT_INFO_ETICA_DEONTOLOGIA_TEXT}

--- SEPARADOR DE DOCUMENTOS ---

${CODIGO_DEONTOLOGICO_TEXT}
`;
